#!/bin/bash

# world wide not readable
umask 077

dest=/var/backups/acl
destfile=$dest/dump-$(date -I).xz

# backup file acls
# redirect stderr to prevent "getfacl: Entferne führende '/' von absoluten Pfadnamen" 
getfacl -R / 2> /dev/null | xz -5 > $destfile

# expire dumps older than a week (there are still on the backup server)
find $dest -maxdepth 1 -type f -mtime +7 -name "*.xz" -delete
